### ISSUE TITLE
Error when launching minecraft using brd

### ISSUE THREAD

**Issue by arepopo** [ddf8196/BetterRenderDragon#11]
![Screenshot 2023-06-06 012644](https://github.com/ddf8196/BetterRenderDragon/assets/135648182/fef09df5-1b9b-400b-aace-5b7bc76c64b0)

i get this error when launching minecraft, did i do something wrong? latest official mc, i did add exception to the brd folder too incase if it's antivurs problem

**Comment by vrfo** [comment]
i get this too i really dont know the provlem

**Comment by miqumi** [comment]
reinstall then speak 🙏






clear the BRD folder and re-extract

**Comment by miqumi** [comment]
reinstall then speak 🙏






||clear the BRD folder and re-extract||

**Comment by miqumi** [comment]
reinstall then speak 🙏






||clear the BRD folder and re-extract||
<@994811475317243955>

**Comment by miqumi** [comment]
reinstall then speak 🙏






||clear the BRD folder and re-extract||
<@983667490850734080>
