### ISSUE TITLE
How to run in mobile

### ISSUE THREAD

**Issue by Abbasannn** [ddf8196/BetterRenderDragon#12]
Please tell me how to run in mobile

**Comment by Arctrometa** [comment]
BetterRD doesn't exist for mobile, join the YSS discord and get PatchApp from there to run shaders as resource packs.

**Comment by ImHere687** [comment]
I also can’t figure it out

**Comment by Arctrometa** [comment]
you cannot use BetterRD on mobile. just join the YSS discord server to know more.

**Comment by ENDERMANYK** [comment]
get the same technology program Materialbinloader and patch the libminecraftpe.so then repack the apk to load the shader

**Comment by ddf8196** [comment]
BetterRenderDragon only supports windows x64
