### ISSUE TITLE
Unable to access features of "Vanilla2Deffered"

### ISSUE THREAD

**Issue by Rgdevil420** [ddf8196/BetterRenderDragon#13]
![image](https://github.com/ddf8196/BetterRenderDragon/assets/88793051/bb5bec03-d491-4e7e-a382-65d7021ba992)

When i opened the program through "Minecraft.bat" I can access all features of the window except for the module "Vanilla2Deffered" and i need to disable rtx but i cant.

Also, when i try to go in a world with shaders enabled(YSS RD 1.9.8), no blocks are renderred 
![image](https://github.com/ddf8196/BetterRenderDragon/assets/88793051/eed6bef8-7b71-4d3d-8f75-ddb1997df110)

I've tried reinstalling the program but nothing seems to work ive checked my directx version and its up to date

**Comment by ddf8196** [comment]
This indicates that the game is running on D3D11. The Vanilla2Deferred module will be disabled on D3D11, as it is currently not possible to enable deferred rendering on D3D11, and there is no sense in disabling RTX on D3D11, as RTX is already disabled

**Comment by Rgdevil420** [comment]
> This indicates that the game is running on D3D11. The Vanilla2Deferred module will be disabled on D3D11, as it is currently not possible to enable deferred rendering on D3D11, and there is no sense in disabling RTX on D3D11, as RTX is already disabled
Oh, ok thanks
btw is there any way to fix that renderring issue?(second image)
