### ISSUE TITLE
does not work for 1.20.1

### ISSUE THREAD

**Issue by Kna5234** [ddf8196/BetterRenderDragon#16]

**Comment by Kna5234** [comment]
through git hub went to releases then downloaded the zip file NOT THE SOURCE CODE

**Comment by Arctrometa** [comment]
are you launching the game from the bat file? It is required for you to launch the game using the BetterRD launchmincraft.bat file to use BetterRD.

**Comment by Gabriel21Paixao** [comment]
Same here, I was developing my shaders and it stopped of working

**Comment by Kna5234** [comment]
I think it's cause 1.20.1

**Comment by ddf8196** [comment]
[v1.3.3](https://github.com/ddf8196/BetterRenderDragon/releases/tag/v1.3.3)
