### ISSUE TITLE
it's just not working

### ISSUE THREAD

**Issue by Uzcoin404** [ddf8196/BetterRenderDragon#18]
Minecraft version: 1.20.1
Directx version: 12
if I click launchMinecraft.bat file it's just opening Minecraft and there's no render dragon ui. I've clicked f6 but not worked, installed shaders but nothing happened

**Comment by BBCBruh** [comment]
You Need GTX/RX GPU

**Comment by BBCBruh** [comment]
> Minecraft version: 1.20.1
> Directx version: 12
> if I click launchMinecraft.bat file it's just opening Minecraft and there's no render dragon ui. I've clicked f6 but not worked, installed shaders but nothing happened

You Need GTX/RX GPU

**Comment by Uzcoin404** [comment]
Oh thanks for your response
My laptop has only Intel builtin GPU so there is no way to use shaders?

**Comment by BBCBruh** [comment]
> Oh thanks for your response
> My laptop has only Intel builtin GPU so there is no way to use shaders?

Please Switch to Java First
