### ISSUE TITLE
Deferred Rendering not working

### ISSUE THREAD

**Issue by Darklight65136** [ddf8196/BetterRenderDragon#19]
minecraft version:1.20.1
DirectX version:12
Cannot enable referred rendering
![%ZM06F5BS0H_NC0@ON%~PS7](https://github.com/ddf8196/BetterRenderDragon/assets/138889920/22cf544b-410e-470f-9cbc-a95a2f088a7b)

I installed the RTX resource pack,press "ctrl+;" then it shows that deferred rendering is enabled, but it has no effect in the game
I restart minecraft,but still not working
![49VTW V6 1H{_C4HBO$(P_E](https://github.com/ddf8196/BetterRenderDragon/assets/138889920/ccc3e377-bde7-4a41-8fab-de982699e934)

**Comment by gaminglnk** [comment]
Same issue, my laptop has Nvidia MX110 gpu with 2GB dedicated ram for it.

**Comment by Arctrometa** [comment]
if you're on 1.20.30, it won't work. BetterRD currently does not support 1.20.30 or .31

**Comment by sinaSPOGames** [comment]
i am on 1.20.62 stable and it crashes when trying to load
same GPU MX110 2gb on Lenovo Laptop
Dx11

**Comment by sinaSPOGames** [comment]
the funny thing is it was enabled by default and i cant disable it...
