### ISSUE TITLE
Worked 3 days ago and now it won't

### ISSUE THREAD

**Issue by WastedGTAZ** [ddf8196/BetterRenderDragon#20]
Hi so I'm getting on MC Bedrock edition to play with a friend of mine, and 3 nights ago we played and the shaders and everything worked and now the ui won't pull up, why?

**Comment by grliiedcheese** [comment]
You can pull up the ui by pressing F6, you may have to hold Ctrl, Alt, or Shift while pressing it if you are on a laptop.
