### ISSUE TITLE
Two Minecraft updates broke it since the last brd update.

### ISSUE THREAD

**Issue by OvrDragon224** [ddf8196/BetterRenderDragon#26]
I really hope this developer stops being this lazy all the time. Maybe update it when a Minecraft update comes out.

**Comment by ENDERMANYK** [comment]
he is busy with optimized android deferred, what you mean lazy Bruh

**Comment by notnathane** [comment]
just wondering, but what is the progress on the update? as in will the update be coming soon?
take your time on it though

**Comment by OvrDragon224** [comment]
Sorry.
