### ISSUE TITLE
Vanilla2Deffered still unavailable no matter what I do.

### ISSUE THREAD

**Issue by UhhHello12** [ddf8196/BetterRenderDragon#27]
I updated BetterRenderDragon to 1.3.3 and after that the Vanilla2Deffered option just won't work and won't let me edit anything. I checked if my DirectX was on 12 and it was, then I checked if Direct3D acceleration was enabled, and it was. I am not sure what the problem is, if anyone can help me i would be very grateful.

**Comment by UhhHello12** [comment]
Also the shaders do not work, I think it is because of this issue that I am having.

**Comment by Arctrometa** [comment]
Currently 1.20.10/12 is not supported by BetterRD.

**Comment by UhhHello12** [comment]
Oh okay thanks. Hopefully the creator updates it soon.
