### ISSUE TITLE
아직 1 20 10으로 업데이트하지 않았습니다.

### ISSUE THREAD

**Issue by OvrDragon224** [ddf8196/BetterRenderDragon#29]

**Comment by OvrDragon224** [comment]
Hopefully that will get his attention.

**Comment by ddf8196** [comment]
我懂英语，不懂韩语，韩语才需要用翻译软件

**Comment by SuperLlama88888** [comment]
Come on @OvrDragon224, you call it "easy" to add 1.20.10 support. If it's so easy, why don't you do it yourself? I've tried to read this codebase before and haven't got a deep understanding of how this amazing piece of software functions. Commenting 4 times won't fix it any faster, it just wastes the developers' time. As mentioned in another comment, ddf has been busy IRL and hasn't had the time to do it. Stop calling ddf "lazy" and do something useful.
