### ISSUE TITLE
Can you help me ?

### ISSUE THREAD

**Issue by VioletOnion** [ddf8196/BetterRenderDragon#34]
I want to use it in version 1.20.12.01. I found the signature of the "readfile" function in 1.20.12.01, which should be "48 89 5C 24 08 48 89 7C 24 20 55 48 8D 6C 24 D0". However, I checked it and found that it was not called. May I ask if there are any issues with it ? Can you help me, thank you.

**Comment by miqumi** [comment]
you can, compile by self.
1. Have VS Code
2. `git clone https://github.com/ddf8196/BetterRenderDragon.git`
3. i think you know it
