### ISSUE TITLE
The GUI does not open.

### ISSUE THREAD

**Issue by choa5913** [ddf8196/BetterRenderDragon#40]
I've tried reinstalling Better RD and the game, and I've also pressed F6 multiple times, but the GUI still doesn't open.

https://github.com/ddf8196/BetterRenderDragon/assets/143405177/b9b30e4b-9e13-49d9-8804-cf5820b2ddd9

**Comment by nhatquan208** [comment]
same me bro
i don't know how to fix that ://

**Comment by duster-san** [comment]
me too bro

**Comment by Ree6e** [comment]
install this https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
