### ISSUE TITLE
game crash with rtx supported pack and deferred rendering enabled on featured servers

### ISSUE THREAD

**Issue by agiert** [ddf8196/BetterRenderDragon#42]
every time i want to use shaders on servers from the featured servers list in minecraft my game crashes.
mc version: 1.20.15
brd version: latest

https://github.com/ddf8196/BetterRenderDragon/assets/123122829/2303cfbf-d2ed-480c-bec5-135cf6b28e28

**Comment by miqumi** [comment]
game prob thinks you're using hacks (brd)

**Comment by agiert** [comment]
> game prob thinks you're using hacks (brd)

i don think thats it because i only cant have it enabled in the hub (on hive) or in a game (on cubecraft)

**Comment by miqumi** [comment]
> > game prob thinks you're using hacks (brd)
> 
> i don think thats it because i only cant have it enabled in the hub (on hive) or in a game (on cubecraft)

hmm lemme try
