### ISSUE TITLE
Shaders not loading anymore

### ISSUE THREAD

**Issue by Linkshae** [ddf8196/BetterRenderDragon#43]
I used version 1.3.4 with no issues with YSS_RD_Beta1_1.19.60+ and also used Musk Rose RD Base v4.0 without a problem but they have suddenly stopped working even when loaded? This is also happening with every other shader I try they are loaded in global resources but don't do anything ingame.

**Comment by JustARenderDragonHater** [comment]
A New Update Of Minecraft Released, It Was Called 1.20.30. But BetterRenderDragon Only Supports 1.20.10-1.20.15 Not The Latest Version. I Also Heard They Were Working On BetterRenderDragon For 1.20.30 (I Heard It From yss Discord) So It's Whether You Have To Downgrade To 1.20.15. Or You wait For BetterRenderDragon Latest Version To Come.

**Comment by miqumi** [comment]
> A New Update Of Minecraft Released, It Was Called 1.20.30. But BetterRenderDragon Only Supports 1.20.10-1.20.15 Not The Latest Version. I Also Heard They Were Working On BetterRenderDragon For 1.20.30 (I Heard It From yss Discord) So It's Whether You Have To Downgrade To 1.20.15. Or You wait For BetterRenderDragon Latest Version To Come.

This is such a british statement
I hate your name

**Comment by BluePixels09277** [comment]
Im Not British, Im Not Hating On REAL Render Dragon I Hated That They Don't allow Real Shaders. Bro Thought That I Was hating On BetterRenderDragon 💀💀💀 I Like BetterRenderdragon, Espescially The Preview Where They allowed To Use Shaders. I Just Replied To help Someone.

**Comment by miqumi** [comment]
> Im Not British, Im Not Hating On REAL Render Dragon I Hated That They Don't allow Real Shaders. Bro Thought That I Was hating On BetterRenderDragon 💀💀💀 I Like BetterRenderdragon, Espescially The Preview Where They allowed To Use Shaders. I Just Replied To help Someone.

nah, I didnt think you were hating on BRD
the (goddamn beautiful) shaders you are using rn is made possible because of the RenderDragon engine that is inside minecraft.
Dont hate on anything without  knowing what it is

**Comment by BluePixels09277** [comment]
I Didn't Know That Render Dragon Released Because Mojang Was Preparing For The Deffered Rendering Update

**Comment by miqumi** [comment]
> I Didn't Know That Render Dragon Released Because Mojang Was Preparing For The Deffered Rendering Update

Deferred isn't the ONLY thing RenderDragon can do. It's much MUCH more capable
