### ISSUE TITLE
Official Version 1.20.30 Support

### ISSUE THREAD

**Issue by BluePixels09277** [ddf8196/BetterRenderDragon#44]
This Is a request, Not an Issue. I Tried Better Render Dragon in Latest Official Version Of Minecraft (1.20.30). It Didn't Work. Right Now BetterRenderDragon Only Support 1.20.10-1.20.15, It Dosen't Support Latest Version. So My Idea Is Add Support For 1.20.30! Maybe A BetterRenderDragon 1.3.6 Will Release

**Comment by Arctrometa** [comment]
an update is in the works.
