### ISSUE TITLE
Support for 1.20.31!

### ISSUE THREAD

**Issue by Kingflooflol** [ddf8196/BetterRenderDragon#45]
I noticed that my mc auto updates and i cant use older versions so im stuck at 1.20.31 and really wanna use shaders so it would be cool if theres a support for 1.20.31!!!!

**Comment by ConCrafter20** [comment]
i think it is gonna take a while they are not even done with [1.20.30](https://github.com/ddf8196/BetterRenderDragon/issues/44#issuecomment-1735484772)

**Comment by zrannx** [comment]
.30 and .31 work the same , so if ddf is gonna update to one then both are going to work

**Comment by ConCrafter20** [comment]
ok

**Comment by miqumi** [comment]
Close it; no longer relevant
