### ISSUE TITLE
1.20.51 support

### ISSUE THREAD

**Issue by dreamdoggo69** [ddf8196/BetterRenderDragon#54]
uhhh i  tried using this and it doesn't work but I guess there's  still not a 1.20.51 support so uhh make one right now or  you'll never see your family ever again

**Comment by ddf8196** [comment]
v1.3.7 supports 1.20.51

**Comment by dreamdoggo69** [comment]
Fr

**Comment by dreamdoggo69** [comment]
bro it doesnt support 1.20.61 i just tried

**Comment by ddf8196** [comment]
1.20.61 has not been released, and I have tested it on all versions of 1.20.60.x and it all works fine

**Comment by dreamdoggo69** [comment]
i meant 1.20.51 sorry
