### ISSUE TITLE
better render dragon not working

### ISSUE THREAD

**Issue by TTmasa22** [ddf8196/BetterRenderDragon#57]

**Comment by TTmasa22** [comment]
I run launchminecraft.bat and Minecraft starts up, but it shows a red screen and does not load. (pc setup: windows11 pro 23h2 core i7 4770 gtx1060 DirectX 12)

**Comment by adnanosama** [comment]
same

**Comment by AmbrizAlberto** [comment]
same

**Comment by AmbrizAlberto** [comment]
same

**Comment by Vsky123** [comment]
not the same as mine. But hope this can fix https://youtu.be/qiZd5hDYgDM
