### ISSUE TITLE
Clicking reload shader causes to bug out the textures

### ISSUE THREAD

**Issue by Fevirre** [ddf8196/BetterRenderDragon#60]
![image](https://github.com/ddf8196/BetterRenderDragon/assets/77900806/ed0ce404-acb2-4eec-8618-701ad899291b)

**Comment by ddf8196** [comment]
What shaders are you using?

**Comment by Fevirre** [comment]
Yss special edition, this also happens with Luminous dreams or any deferred pack of the matter

**Comment by ddf8196** [comment]
Currently, yss se is not supported in preview 1.20.70.24 and later because mojang changed the name of a texture. You can try to use preview versions before 1.20.70.22, or the 1.20.62 release version
