### ISSUE TITLE
BTR 1.4.1 Security Problem

### ISSUE THREAD

**Issue by ThatGuy2439** [ddf8196/BetterRenderDragon#64]
When downloading the latest version of BetterRenderDragon, Windows find a virus in the file just like the previous version. But this time the virus is now "Trojan:Win32/Znyonm" and is labeled by Microsoft Security as a severe threat. Please send feedback about the safety of the release. Thanks, much appreciated!

**Comment by ddf8196** [comment]
Check the hash to ensure that the downloaded file has not been modified. If the hash matches, then it's a false positive, like #58

**Comment by miqumi** [comment]
false positive.

**Comment by ThatGuy2439** [comment]
I checked it and it was a false positive, but Windows Security is automatically deleting the file for security reasons

**Comment by miqumi** [comment]
> I checked it and it was a false positive, but Windows Security is automatically deleting the file for security reasons

add it as an exception in windows security
