### ISSUE TITLE
Shaders not working

### ISSUE THREAD

**Issue by ERENPROO** [ddf8196/BetterRenderDragon#65]
Did I miss a step or no? Since I installed it, opened launchminecraft.bat and loaded the shader.

MCBE version: 1.20.73
RAM: 4GB
CPU: Intel Core i3-3217U
GPU: Intel HD Graphics 4000

Is it not compatible with 1.20.73? Since it says it's for versions 1.20.10 and upper.

**Comment by Arctrometa** [comment]
Are you trying to use Deferred or any other shaders that build upon the deferred rendering pipeline (YSS SE as an example). ?

**Comment by Arctrometa** [comment]
use BetterRD 1.4.0 for Minecraft 1.20.73

**Comment by ERENPROO** [comment]
> use BetterRD 1.4.0 for Minecraft 1.20.73

Will try, thanks.

**Comment by ERENPROO** [comment]
![resim_2024-04-04_164453288](https://github.com/ddf8196/BetterRenderDragon/assets/89633652/5de39d4c-cd79-43e7-8204-1de26cd47b56)
Thank you so much, it worked.

**Comment by imnotjoan** [comment]
hi, where did you get version 1.4.0? I haven't been able to find it

**Comment by ERENPROO** [comment]
> hi, where did you get version 1.4.0? I haven't been able to find it

https://github.com/ddf8196/BetterRenderDragon/releases/tag/v1.4.0
