### ISSUE TITLE
Is there a way to rebind R to reload shaders?

### ISSUE THREAD

**Issue by ERENPROO** [ddf8196/BetterRenderDragon#66]
I was typing in chat and whenever I had to use the R button, it reloads the terrain and makes the game lag for some insignificant amount of time. But leaves a strain on the computer.

**Comment by miqumi** [comment]
fixed in the latest upd-ate

**Comment by ERENPROO** [comment]
> fixed in the latest upd-ate
> 

If that update is 1.4.1, it doesn't work on me.
