### ISSUE TITLE
1.20.81

### ISSUE THREAD

**Issue by Zyfix1** [ddf8196/BetterRenderDragon#68]
Betterrenderdragon not working on 1.20.81

**Comment by EgorimM** [comment]
Me too. I hope you don't mind if I join this discussion?

**Comment by ZeinMaru** [comment]
Me too, I just downloaded Minecraft on PC and I want to play using shaders, but I can't

**Comment by UserX0001** [comment]
![image](https://github.com/ddf8196/BetterRenderDragon/assets/168092625/aa476e6b-1598-4279-a80b-925dd3791154)
I'm not crashed, but when i use BetterRenderDragon, Every block and entity does not be shown.

**Comment by remidu64** [comment]
i think we gotta wait for the next update
