### ISSUE TITLE
BRD not working with 1.20.80+

### ISSUE THREAD

**Issue by remidu64** [ddf8196/BetterRenderDragon#69]
BRD 1.4.3 isn't working with 1.20.80+
Maybe you're waiting for 1.20.90 / 1.21.XX but please fix the 1.20.80 problem first
Thanks in advance

**Comment by miqumi** [comment]
https://github.com/ddf8196/BetterRenderDragon/issues/68
One issue already exists

**Comment by sinaSPOGames** [comment]
> #68 One issue already exists

include newer issues #67 #76 #57

**Comment by remidu64** [comment]
1.21 won't work because mojang a file that allowed mods to be made without having to reverse engineer the whole version

**Comment by miqumi** [comment]
> 1.21 won't work because mojang removed a file that allowed mods to be made without having to reverse engineer the whole version
> 
> edit: i forgor a word

nah, PDB is still there+ Its only in the server files NOT the game's files.

**Comment by EnderBoy2000** [comment]
you got it wrong, that has nothing to to with betterrdOn 24. Jun 2024, at 09:56, remidu64 ***@***.***> wrote:﻿
1.21 won't work because mojang a file that allowed mods to be made without having to reverse engineer the whole version

**Comment by miqumi** [comment]
> you got it wrong, that has nothing to to with betterrdOn 24. Jun 2024, at 09:56, remidu64 ***@***.***> wrote:﻿ 1.21 won't work because mojang a file that allowed mods to be made without having to reverse engineer the whole version —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

yeah
