### ISSUE TITLE
BRD 1.4.3 dll

### ISSUE THREAD

**Issue by Skyelur** [ddf8196/BetterRenderDragon#70]
where can I download the dll file for BRD 1.4.3? Cause I want to replace the dll file in BRD 1.4.1

EDIT: It's okay now, thanks

**Comment by PhoeLycia** [comment]
bro where did u find it?

**Comment by PhoeLycia** [comment]
> > bro where did u find it?
> 
> actions tab brother

thx a lot bro.

**Comment by fartbuckle34** [comment]
> > > bro where did u find it?
> > 
> > 
> > actions tab brother
> 
> thx a lot pls help me it says its expired
