### ISSUE TITLE
Please change the reload shaders hotkey.

### ISSUE THREAD

**Issue by Death62733** [ddf8196/BetterRenderDragon#71]
I am here to ask/beg for you guys or/and girls to change the shader reload hotkey to something else like f10 for example because r can and is many peoples hotkey for something in games and getting used to new hotkeys is not so easy. Thank you for listening.

**Comment by fluffyball9** [comment]
It's removed in 1.4.3

**Comment by Death62733** [comment]
do you know when that will be released since highest version rn says 1.4.1

**Comment by fluffyball9** [comment]
You can use the 1.4.1 zip and replace dlls/BetterRenderDragon.dll with one from the actions tab and then 1.4.3 on the top of this page
