### ISSUE TITLE
launch 'launchminecraft.bat' only open minecraft, but the running window has crashed

### ISSUE THREAD

**Issue by berry-e** [ddf8196/BetterRenderDragon#72]
And i finally launch origin MC without launching BRD. But 'launchminecraftpreview.bat' has not this problem . i don't remember how i do any changes to it ,but problem still exists even if i download a new BRD and install it

**Comment by miqumi** [comment]
open `launchminecraft.bat` and then if it closes, start minecraft from the start menu. It'll still have BRD loaded. No Idea why it works.
