### ISSUE TITLE
BetterRenderDragon-1.4.1.zip is detected as a virus

### ISSUE THREAD

**Issue by Rabpixie** [ddf8196/BetterRenderDragon#73]
Using VirusTotal website BetterRenderDragon-1.4.1 is detected as a virus

Download the .zip from this link:

https://github.com/ddf8196/BetterRenderDragon/releases/tag/v1.4.1

 which as far as I know is the official download page
 
 
![image](https://github.com/ddf8196/BetterRenderDragon/assets/167242874/2fb64ab3-ece4-4bd4-ae30-40c7278d7188)

is this a false flag?

why it is target as a virus?

**Comment by fluffyball9** [comment]
It's probably detected as a virus because it works by hacking into Minecraft's memory and hacking into memory is usually considered dangerous by antivirus.

see #64

**Comment by IshAlah** [comment]
> Вероятно, он определяется как вирус, потому что он работает путем взлома памяти Minecraft, а взлом памяти антивирус обычно считает опасным.
> 
> см. [ № 64 ](https://github.com/ddf8196/BetterRenderDragon/issues/64)
Then I have another question, why is there an error in the command line when I run brd without internet?
