### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by ep913** [ddf8196/BetterRenderDragon#79]
i heard 1.4.3 is out, but it says latest is 1.4.1 and supports 1.20.80/81, even one of the last post's comments says 1.4.3 is out.... but it says 1.4.1 is latest. so update it to 1.21.0/ 1.21.1
![image](https://github.com/ddf8196/BetterRenderDragon/assets/173689657/c0d24d80-3108-4694-ac7d-610ec80c9d3d)

**Comment by ENDERMANYK** [comment]
1.4.3 link :https://github.com/ddf8196/BetterRenderDragon/actions/runs/8843461193

**Comment by ep913** [comment]
where is the zip file, i dont know how to use the dll or pdb
also i thought u need to have launchminecraft.bat or do u just inject betterrenderdragon into minecraft?

**Comment by ep913** [comment]
oh wait nevermind the .dll file is a zip

**Comment by ep913** [comment]
how do i use the .dll file i injected it into minecraft but it just crashed my game

**Comment by miqumi** [comment]
bro 👽👽👽👽👽👽👽👽👽👽
wtf happened here

**Comment by miqumi** [comment]
> how do i use the .dll file i injected it into minecraft but it just crashed my game

drop it in the BRD folder (the folder which has LaunchMinecraft.bat)

**Comment by zzx587** [comment]
my blocks dont load with the 1.4.3 dll, im in 1.21

**Comment by EnderBoy2000** [comment]
If you are using any shaders rn, that probably means they are not supportedOn 25. Jun 2024, at 18:02, zzx587 ***@***.***> wrote:﻿
my blocks dont load with the 1.4.3 dll, im in 1.21

**Comment by EnderBoy2000** [comment]
you download the dll and them download the latest full release version from downloads tab and then just replace the dll with 1.4.3 dllOn 25. Jun 2024, at 07:40, ep913 ***@***.***> wrote:﻿
where is the zip file, i dont know how to use the dll or pdb
also i thought u need to have launchminecraft.bat or do u just inject betterrenderdragon into minecraft?

**Comment by ep913** [comment]
i found a comment that had 1.4.3 .zip link https://github.com/ddf8196/BetterRenderDragon/issues/76.

**Comment by helloo4** [comment]
fps loked at 120hz? i have 240hz monitor before use better render dragon in minecraft appeared fps options and I could set it to unlimited after use better render dragon That option disappeared, is it normal? If so, could you implement an option to unlock the fps?.

**Comment by miqumi** [comment]
> fps loked at 120hz? i have 240hz monitor before use better render dragon in minecraft appeared fps options and I could set it to unlimited after use better render dragon That option disappeared, is it normal? If so, could you implement an option to unlock the fps?.

most def not brd's problem
