### ISSUE TITLE
 version not available 1.4.3 why?

### ISSUE THREAD

**Issue by Dannyredz** [ddf8196/BetterRenderDragon#86]
when i click on version 1.4.3 to download it, it says ''This content is no longer available.'' why that because other people can use it or is it still in work?

**Comment by miqumi** [comment]
Discord just changed their link formats.
Join the [YSS discord server](https://discord.gg/yss) and check #better-rd channel

**Comment by DuwlianMLG** [comment]
discord server link its down, yss page discord server link its also downed, or idk it doesnt work

**Comment by miqumi** [comment]
Ive updated it, try again
