### ISSUE TITLE
textures are not loading/everything is invisible

### ISSUE THREAD

**Issue by DignityWG** [ddf8196/BetterRenderDragon#88]
![Screenshot_20240712-010337](https://github.com/ddf8196/BetterRenderDragon/assets/175344256/fb270f44-fb42-4f7b-90c7-c286b6694216)
I just started using render dragon and for some reason all of the blocks are invisible when im using a shader

**Comment by EnderBoy2000** [comment]
then that shader is probably incompatible with the version. Try YSS RDOn 11. Jul 2024, at 19:05, DignityWG ***@***.***> wrote:﻿
Screenshot_20240712-010337.jpg (view on web)
I just started using render dragon and for some reason all of the blocks are invisible when im using a shader
