### ISSUE TITLE
Not working in 1.21.2

### ISSUE THREAD

**Issue by GazaMaruta** [ddf8196/BetterRenderDragon#91]
i did all the steps, put the mcpack in the render dragon folder, opened minecraft through launchminecraft.bat, installed the mcpack, and i just get vanilla minecraft, but without clouds.

**Comment by MRUIAW** [comment]
oh, here, use the version in the actionm
https://github.com/ddf8196/BetterRenderDragon/actions/runs/9884141130

**Comment by GazaMaruta** [comment]
> oh, here, use the version in the action https://github.com/ddf8196/BetterRenderDragon/actions/runs/9884141130

what do you mean by that? im sorry, im not good at this.

**Comment by MRUIAW** [comment]
![QQ_1722371995123](https://github.com/user-attachments/assets/4a5db2b4-a79d-40e9-b9b9-3010938921dc)

**Comment by MRUIAW** [comment]
> > oh, here, use the version in the action https://github.com/ddf8196/BetterRenderDragon/actions/runs/9884141130
> 
> what do you mean by that? im sorry, im not good at this.
> 
> edit : hey, i tried downloading the dll you linked me and replacing the original one, now it have better lighting and not vanilla minecraft. but now the console doesnt appear and theres no shadows.
> 
> edit again : the newb x legacy turns out dont have the kind of shadows im looking for, ignore the shadow comment. yeah my problem now is the console doesnt appear now.

![QQ_1722371995123](https://github.com/user-attachments/assets/4a5db2b4-a79d-40e9-b9b9-3010938921dc)
