### ISSUE TITLE
dosent work for 1.21.2

### ISSUE THREAD

**Issue by ep913** [ddf8196/BetterRenderDragon#93]
is this for me or does it not support yet?

**Comment by ep913** [comment]
NVM i downloaded the latest action and it worked

**Comment by drinkwater6969** [comment]
how did you do that?

**Comment by fuadxtps23** [comment]
> how did you do that?

latest dll
https://github.com/ddf8196/BetterRenderDragon/actions/runs/9884141130

**Comment by drinkwater6969** [comment]
thanks

**Comment by jaydenyt139** [comment]
i changed the dll and its still not working for me, any solutions?
