### ISSUE TITLE
BETTER RENDER DRAGON ARE DIDN'T WORKING ON MY WINDOWS 11

### ISSUE THREAD

**Issue by DamnFreak** [ddf8196/BetterRenderDragon#94]
I have put the shaders to global resource pack, but it still same, shaders can't be loaded, is Material bin loader doesn't support on windows 11?
![Screenshot 2024-07-29 084921](https://github.com/user-attachments/assets/d03fdd96-604c-4543-bf0a-a38ba261be08)

**Comment by MRUIAW** [comment]
what is your minecraft version?

**Comment by Jeppapa** [comment]
I have the same problem (1.21.2). I've enabled materialbinloader, put it in global resources and everything but still can't load shaders. OP probably can't load because force enable deferred technical preview in on.
