### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Hans2112** [ddf8196/BetterRenderDragon#96]
Can anyone help me with my betterrenderdragon it doesnt work and when i read the other problem that says that it doesnt work i read that i need to download the new dll but after i download the new dll and replace my old dll it still doesnt work and my render dragon menu is gone please help me i dont understand how it works (My minecraft version is 1.21.2)

**Comment by andra-spec** [comment]
betterrenderdragon only supports minecraft version 1.20.80 or lower

**Comment by Arctrometa** [comment]
> betterrenderdragon only supports minecraft version 1.20.80 or lower

No it doesn't. Get the latest build of BetterRD from the actions tab or join the YSS discord.

**Comment by Jeppapa** [comment]
It's best to just update the download link in readme lol.. it's not that hard

**Comment by Hans2112** [comment]
Thanks for the info guys
